name: Unity Tests
env:
  UNITY_VERSION: 2022.3.7f1
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:      
      - name: Run Tests
        id: unity-test
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          unityVersion: 2022.3.7f1
          testMode: all
          artifactsPath: test-results
