name: Run .NET Script

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-script:
    name: Run CSX Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install dotnet-script
        run: dotnet tool install -g dotnet-script

      - name: Run CSX file
        run: |
          export PATH="$PATH:/root/.dotnet/tools"
          dotnet script @Build/update_and_build.csx
        working-directory: ${{ github.workspace }}

      # 스크립트 실행 결과를 아티팩트로 저장 (선택사항)
      - name: Upload script results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: script-results
          path: |
            @Build/output/**
            @Build/logs/**
          retention-days: 7
